# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c35d679d9f459ecda0e2d2222f677f98f6a0aa1da742b9990a66229f6d07918c8bb3899a229debaf585e329497a883e424863251684db62eafb5e3dac4bf327f

test:
  secret_key_base: 42b3285c8b0ffa979894699aa9b38dd06806ae97e4d3151bfd630a4e4a98d1d22d6bcda0a0bf8faa9a44b8e27013085ffe3397b98fe39b361c8617b5effa3f92

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
